export const SET_DATA = 'SET_DATA';

export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

export const INITIAL_CORRECT_PERCENTAGES = 'INITIAL_CORRECT_PERCENTAGES';
export const CORRECT_PERCENTAGES = 'CORRECT_PERCENTAGES';
export const ITEM_ISOLATED_CHANGE = 'ITEM_ISOLATED_CHANGE';
